"use strict";
exports.__esModule = true;
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getProducts();
console.log(result);
result = _productService.getById(3);
console.log(result);
var p = new Product_1.Product(5, "Ali", "Deneme", 125);
_productService.saveProducts(p);
result = _productService.getProducts();
console.log(result);
